server:
  port: 8849
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: Minifier
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 12
    lettuce:
      pool:
        max-active: 16
        max-wait: 3000ms
        max-idle: 16
        min-idle: 0

project:
  server-config:
    # 服务域名，不要 / 结尾，形如: http://wwww.minifier.cn，http://localhost:8849
    domain: http://localhost:8849